var user=
{
  "login": "maxehnert",
  "id": 8755250,
  "avatar_url": "https://avatars.githubusercontent.com/u/8755250?v=2",
  "gravatar_id": "",
  "url": "https://api.github.com/users/maxehnert",
  "html_url": "https://github.com/maxehnert",
  "followers_url": "https://api.github.com/users/maxehnert/followers",
  "following_url": "https://api.github.com/users/maxehnert/following{/other_user}",
  "gists_url": "https://api.github.com/users/maxehnert/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/maxehnert/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/maxehnert/subscriptions",
  "organizations_url": "https://api.github.com/users/maxehnert/orgs",
  "repos_url": "https://api.github.com/users/maxehnert/repos",
  "events_url": "https://api.github.com/users/maxehnert/events{/privacy}",
  "received_events_url": "https://api.github.com/users/maxehnert/received_events",
  "type": "User",
  "site_admin": false,
  "name": "max ehnert",
  "company": "",
  "blog": "",
  "location": "Atlanta",
  "email": "",
  "hireable": true,
  "bio": null,
  "public_repos": 14,
  "public_gists": 0,
  "followers": 0,
  "following": 1,
  "created_at": "2014-09-12T23:08:22Z",
  "updated_at": "2014-10-08T17:36:07Z"
}
